sensor:
  - platform: template
    id: batteryLevelSensor
    name: "Battery level"
    icon: "mdi:battery"
    unit_of_measurement: mAh
    lambda: |-
      esphome::mower::Automower *mower = (esphome::mower::Automower *) id(mower_id);
      return {mower->get_battery_level_sensor()->state};

  - platform: template
    id: chargingTimeSensor
    name: "Charging time"
    icon: "mdi:battery-clock"
    unit_of_measurement: min
    lambda: |-
      esphome::mower::Automower *mower = (esphome::mower::Automower *) id(mower_id);
      return {mower->get_charging_time_sensor()->state};

  - platform: template
    id: mowingTimeSensor
    name: "Mowing time"
    icon: "mdi:av-timer"
    unit_of_measurement: min
    lambda: |-
      esphome::mower::Automower *mower = (esphome::mower::Automower *) id(mower_id);
      return {mower->get_mowing_time_sensor()->state};

  - platform: template
    id: batteryUsedSensor
    name: "Battery used"
    icon: "mdi:battery"
    unit_of_measurement: mAh
    lambda: |-
      esphome::mower::Automower *mower = (esphome::mower::Automower *) id(mower_id);
      return {mower->get_battery_used_sensor()->state};

  - platform: template
    id: batteryVoltageSensor
    name: "Battery voltage"
    icon: "mdi:battery-charging"
    unit_of_measurement: V
    lambda: |-
      esphome::mower::Automower *mower = (esphome::mower::Automower *) id(mower_id);
      return {mower->get_battery_voltage_sensor()->state};

  - platform: template
    id: batteryTemperatureSensor
    name: "Battery temperature"
    icon: "mdi:thermometer-lines"
    unit_of_measurement: "°C"
    lambda: |-
      esphome::mower::Automower *mower = (esphome::mower::Automower *) id(mower_id);
      return {mower->get_battery_temperature_sensor()->state};

  - platform: template
    id: bladeMotorSpeedSensor
    name: "Blade Motor Speed"
    icon: "mdi:saw-blade"
    unit_of_measurement: RPM
    lambda: |-
      esphome::mower::Automower *mower = (esphome::mower::Automower *) id(mower_id);
      return {mower->get_blade_motor_speed_sensor()->state};

  - platform: template
    id: firmwareVersionSensor
    name: "Firmware version"
    icon: "mdi:chip"
    lambda: |-
      esphome::mower::Automower *mower = (esphome::mower::Automower *) id(mower_id);
      return {mower->get_firmware_version_sensor()->state};

  - platform: template
    id: "lv95_e"
    name: "LV95 E"
    lambda: |-
      double phi = id(gps_latitude).state * 3600.0;
      double delta = id(gps_longitude).state * 3600.0;
      double phiPrime = (phi - 169028.66) / 10000;
      double deltaPrime = (delta - 26782.5) / 10000;
      double E = 2600072.37
        + 211455.93 * deltaPrime
        - 10938.51 * deltaPrime * phiPrime
        - 0.36 * deltaPrime * pow(phiPrime, 2)
        - 44.54 * pow(deltaPrime, 3);
      return round(E * 100) / 100.0;

  - platform: template
    id: "lv95_n"
    name: "LV95 N"
    lambda: |-
      double phi = id(gps_latitude).state * 3600.0;
      double delta = id(gps_longitude).state * 3600.0;
      double phiPrime = (phi - 169028.66) / 10000;
      double deltaPrime = (delta - 26782.5) / 10000;
      double N = 1200147.07
        + 308807.95 * phiPrime
        + 3745.25 * pow(deltaPrime, 2)
        + 76.63 * pow(phiPrime, 2)
        - 194.56 * pow(deltaPrime, 2) * phiPrime
        + 119.79 * pow(phiPrime, 3);
      return round(N * 100) / 100.0;

  - platform: template
    id: "lv03_y"
    name: "LV03 Y"
    lambda: |-
      return id(lv95_e).state - 2000000.0;

  - platform: template
    id: "lv03_x"
    name: "LV03 X"
    lambda: |-
      return id(lv95_n).state - 1000000.0;

  - platform: template
    id: "lv95_altitude"
    name: "LV95 Altitude"
    lambda: |-
      double phi = id(gps_latitude).state * 3600.0;
      double delta = id(gps_longitude).state * 3600.0;
      double phiPrime = (phi - 169028.66) / 10000;
      double deltaPrime = (delta - 26782.5) / 10000;
      double h = id(gps_altitude).state - 49.55
         + 2.73 * deltaPrime
         + 6.94 * phiPrime;
      return round(h);
