substitutions:
  name: "automower"
  friendlyName: "Automower"
  timezone: "Europe/Zurich"
  rxpin: "GPIO16"
  txpin: "GPIO17"
  gps_rxpin: "GPIO01"
  baud: "9600"
  osm_bbox: ""

esphome:
  name: ${name}
  friendly_name: ${friendlyName}

time:
#  - platform: homeassistant
#    id: homeassistant_time
#    timezone: ${timezone}
  - platform: gps
    id: gps_time

api:
  encryption:
    key: "YOUR_API"

ota:
  - platform: esphome
    password: "YOUR_OTA"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendlyName} Fallback Hotspot"
    password: "YOUR_AP"

captive_portal:

external_components:
  - source: github://orrpan/esphome-hqam@main
    refresh: always

packages:
  remote_package:
    url: https://github.com/orrpan/esphome-hqam
    ref: main
    refresh: always
    files:
      [
        components/boards/esp32dev.yaml,
        components/confs/base.yaml,
        components/confs/button.yaml,
        components/confs/select.yaml,
        components/confs/sensor.yaml,
        components/confs/textsensor.yaml,
        components/confs/gps.yaml,
      ]
