substitutions:
  name: "automower"
  friendlyName: "Husqvarna Automower 230 ACX"
  timezone: "Europe/Zurich"
  rxpin: "GPIO16"
  txpin: "GPIO17"
  baud: "9600"

esphome:
  name: ${name}
  friendly_name: ${friendlyName}

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: ${timezone}

api:
  encryption:
    key: "YOUR_API"

ota:
  - platform: esphome
    password: "YOUR_OTA"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: "WPA2"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendlyName} Fallback Hotspot"
    password: "YOUR_AP"

captive_portal:

external_components:
  - source: github://xperseguers/esphome-hqam@main
    refresh: always

packages:
  remote_package:
    url: https://github.com/xperseguers/esphome-hqam
    ref: main
    refresh: always
    files:
      [
        components/boards/esp32dev.yaml,
        components/confs/base.yaml,
        components/confs/button.yaml,
        components/confs/select.yaml,
        components/confs/sensor.yaml,
        components/confs/textsensor.yaml,
        components/confs/switch.yaml,
        components/confs/datetime.yaml,
      ]
